[package]
name = "spectrum"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.10"
glam = { version = "0.29.0", features = ["rand"] }
log = "0.4"
pollster = "0.3"
rand = "0.8"
rayon = "1"
wgpu = "22"
winit = { version = "0.29", features = ["rwh_05"] }
